version: "3"

services:
  kafka:
    image: johnnypark/kafka-zookeeper
    container_name: servicekafka
    environment:
      ADVERTISED_HOST: servicekafka
      NUM_PARTITIONS: 3
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - distribuidos

networks:
  distribuidos:
    external: true